cancel_entry: '.cancel'
exit_entry: '.exit'

hotkey_cancel: ['c-z']
hotkey_exit: ['c-x']
hotkey_insert_newline: ['c-i']
hotkey_toggle_word_wrap: ['c-w']
hotkey_new: ['c-n']

temperature: 1.0
max_tokens: 8192

# TerminalModeDialogs dependencies.
terminal_CommandEntryColor2: "ansigreen"
terminal_DisplayCommandOnMenu: false
terminal_PromptIndicatorColor2: "ansicyan"
terminal_ResourceLinkColor: "ansiyellow"

terminal_DialogBackgroundColor: "ansiblue"

terminal_SystemMessageColor: "ansigray"
terminal_SystemMessagePrefix: "🤖"

terminal_ErrorColor: "ansiyellow"

# Leave blank for the current working directory. Can input absolute or relative
# (to current working directory) paths.
chat_history_path: Data/chat_history.txt
chat_log_path: Data/chat_log.txt
system_messages_path: Data/system_messages.json
