ENV PIP_BREAK_SYSTEM_PACKAGES=1

RUN pip install python-dotenv && \
  # PostgreSQL database
  pip install psycopg2-binary && \
  pip install asyncpg && \
  # PDF parsing, extraction, document handling, document processing.
  pip install pymupdf && \
  pip install pyyaml pytest

RUN pip install openai

