ENV PIP_BREAK_SYSTEM_PACKAGES=1

RUN pip install python-dotenv && \
  # PostgreSQL database
  pip install psycopg2-binary && \
  pip install asyncpg && \
  # PDF parsing, extraction, document handling, document processing.
  pip install pymupdf && \
  pip install pyyaml pytest

# https://docs.x.ai/docs/tutorial
RUN pip install openai xai-sdk

