RUN git clone https://github.com/InServiceOfX/chatterbox.git /ThirdParty/chatterbox && \
  cd /ThirdParty/chatterbox && \
  # on branch development, Commits on Jan 30, 2026 and Dec 15, 2025
  git checkout 1d29960c54cf21bd03bd0ae9a239955b183b69be && \
  pip install -e . && \
  cd /
