RUN git clone https://github.com/InServiceOfX/VibeVoice.git /ThirdParty/VibeVoice && \
  cd /ThirdParty/VibeVoice && \
  # on branch master, Commits on Jan 27, 2026
  git checkout a709f13a13a78564c7e1b5e9c48671927546adf8 && \
  pip install -e . && \
  cd /
