# 

RUN git clone https://github.com/InServiceOfX/Qwen3-TTS.git /ThirdParty/Qwen3-TTS && \
  cd /ThirdParty/Qwen3-TTS && \
  # On branch master, Commits on Jan 25, 2026
  git checkout 0af45d81f09f5fcf935d3390fca78785a12c1987 && \
  pip install -e . && \
  cd /
