RUN git clone https://github.com/ysharma3501/LuxTTS.git /ThirdParty/LuxTTS && \
  cd /ThirdParty/LuxTTS && \
  # On branch master, Commits on Jan 25, 2026
  git checkout 6c9979e6ab21b64bf10af6c35d0f4ed52b36d434 && \
  #pip install -e . && \
  pip install -r requirements.txt && \
  cd /
