# accelerate                 1.13.0.dev0                /ThirdParty/accelerate
# diffusers                  0.37.0.dev0                /ThirdParty/diffusers
# flash_attn                 2.7.4.post1+25.11 38114660
# huggingface_hub            1.3.4
# numpy                      2.1.0
# peft                       0.18.2.dev0                /ThirdParty/peft
# qwen-tts                   0.0.4                      /ThirdParty/Qwen3-TTS
# tensorrt                   10.14.1.48
# tokenizers                 0.22.1
# torch                      2.10.0
# torchaudio                 2.10.0
# torchvision                0.25.0
# transformers               5.0.1.dev0                 /ThirdParty/transformers
# vibevoice                  0.0.1                      /ThirdParty/VibeVoice

RUN git clone https://github.com/InServiceOfX/VibeVoice.git /ThirdParty/VibeVoice && \
  cd /ThirdParty/VibeVoice && \
  # on branch master, Commits on Jan 27, 2026
  git checkout a709f13a13a78564c7e1b5e9c48671927546adf8 && \
  pip install -e . && \
  cd /
