# See
# https://docs.sglang.ai/start/install.html#method-2-from-source
# TODO: Consider installing FlashInfer from source for AOT mode for production.
# https://docs.flashinfer.ai/installation.html

RUN git clone https://github.com/InternLM/lmdeploy.git /ThirdParty/lmdeploy && \
    cd /ThirdParty/lmdeploy && \
    pip install -e .



