ARG BASE_IMAGE
FROM ${BASE_IMAGE}

# Set the working directory in the container
# https://docs.docker.com/engine/reference/builder/
ENV THIRD_PARTY=/ThirdParty
WORKDIR ${THIRD_PARTY}

ARG ARCH
ARG PTX

RUN apt-get update && \
  apt-get install --upgrade -y ccache curl libssl-dev && \
  apt install -y git git-lfs && \
  git lfs install



