[package]
name = "core_code"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# https://docs.rs/crate/dotenv/latest
dotenv = "0.15"

[dev-dependencies]
core_code = { path = "." }
