# Install Lean and add to PATH
RUN curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- -y && \
    echo 'export PATH="/root/.elan/bin:$PATH"' >> /root/.bashrc && \
    /bin/bash -c "source /root/.bashrc"

# Update elan and set default Lean version
RUN /root/.elan/bin/elan self update && \
    /root/.elan/bin/elan default leanprover/lean4:stable


# Install Mathlib4
#RUN mkdir -p ~/.local/bin && \
#    curl https://raw.githubusercontent.com/leanprover-community/mathlib4/master/scripts/install_mathlib.sh -sSf | bash

# Update Mathlib4
#RUN lake update




