### Further third party code/repositories

# Python modules from pip that's needed by InServiceOfX.
# Needed to use copali.
RUN pip install --upgrade pdf2image && \
  pip install --upgrade tabula && \
  # Needed to resolve IP address for openjpeg2/libopenjp2
  apt update && \
  # Needed for pdf2image, for pdfinfo command.
  apt-get install -y poppler-utils

#
#
# InServiceOfX
#
#
RUN git clone --no-checkout https://github.com/InServiceOfX/InServiceOfX.git /ThirdParty/InServiceOfX && \
  cd /ThirdParty/InServiceOfX/ && \
  git sparse-checkout init --cone && \
  git sparse-checkout set PythonLibraries/CoreCode && \
  git checkout master && \
  cd / && \
  git clone https://github.com/karpathy/nanoGPT.git /ThirdParty/nanoGPT && \
  cd /
#
#
#
# https://github.com/illuin-tech/colpali.git
#
RUN git clone https://github.com/illuin-tech/colpali.git /ThirdParty/colpali && \
  cd /ThirdParty/colpali && \
  pip install -e .



