RUN python3 -m pip install --upgrade pip && \
  pip install --upgrade ipywidgets && \
  pip install --upgrade numpy && \
  # Upgrading Jinja2 to 3.1 is needed to use apply_chat_template.
  pip install --upgrade jinja2 && \
  # For async API calls to AsyncGroq
  pip install --upgrade pytest-asyncio




