### Further third party code/repositories

# Python modules from pip that's needed by InServiceOfX.
RUN pip install --upgrade pdf2image && \
  pip install --upgrade tabula
#
#
# InServiceOfX
#
#
RUN git clone --no-checkout https://github.com/InServiceOfX/InServiceOfX.git /ThirdParty/InServiceOfX && \
  cd /ThirdParty/InServiceOfX/ && \
  git sparse-checkout init --cone && \
  git sparse-checkout set PythonLibraries/CoreCode && \
  git checkout && \
  cd /ThirdParty/InServiceOfX/PythonLibraries/CoreCode/ && \
  pip install -e . && \
  git clone https://github.com/karpathy/nanoGPT.git && \
  cd /

  

