# https://docs.x.ai/docs/tutorial
RUN pip install groq instructor openai xai-sdk

# apt list --installed
# ccache/noble,now 4.9.1-1 amd64 [installed]
# cmake/noble,now 4.2.0-0kitware1ubuntu24.04.1 amd64 [installed]
# cpp-13/noble-updates,noble-security,now 13.3.0-6ubuntu2~24.04 amd64 [installed,automatic]
# ffmpeg/noble,now 7:6.1.1-3ubuntu5 amd64 [installed]
# g++-13/noble-updates,noble-security,now 13.3.0-6ubuntu2~24.04 amd64 [installed,automatic]
# python3.12/now 3.12.3-1ubuntu0.8 amd64 [installed,upgradable to: 3.12.3-1ubuntu0.9]
# sox/noble,now 14.4.2+git20190427-4build4 amd64 [installed]


