### Further third party code/repositories

#
#
# InServiceOfX
#
#
RUN git clone --no-checkout https://github.com/InServiceOfX/InServiceOfX.git /ThirdParty/InServiceOfX && \
  cd /ThirdParty/InServiceOfX/ && \
  git sparse-checkout init && \
  git sparse-checkout add PythonApplications/CLIChatLocal && \
  git sparse-checkout add PythonLibraries/CoreCode && \
  git sparse-checkout add PythonLibraries/HuggingFace/MoreTransformers && \
  git sparse-checkout add PythonLibraries/ThirdParties/APIs/CommonAPI && \
  git sparse-checkout add PythonLibraries/ThirdParties/APIs/MoreSGLang && \
  git checkout master && \
  cd /

RUN pip install pydantic

RUN apt-get update && apt-get install -y libnuma-dev

#
#
#





