# See
# https://docs.sglang.ai/start/install.html#method-2-from-source
# TODO: Consider installing FlashInfer from source for AOT mode for production.
# https://docs.flashinfer.ai/installation.html

# Originally, the documentation said to install by cloning this specific version:
# git clone -b v0.5.2rc0 https://github.com/sgl-project/sglang.git
RUN git clone https://github.com/sgl-project/sglang.git /ThirdParty/sglang && \
    cd /ThirdParty/sglang && \
    git checkout v0.5.2rc0 && \
    pip install --upgrade pip && \
    pip install -e "python[all]"



