SET(BENCHMARK_CU_SOURCES
  Transformer/Attention/attention_io_benchmark.cu
  )

ADD_EXECUTABLE(AttentionIOBenchmark
  ${BENCHMARK_CU_SOURCES}
  )

TARGET_LINK_LIBRARIES(AttentionIOBenchmark
  MoreCUDAUtilities
  )

SET_TARGET_PROPERTIES(AttentionIOBenchmark
  PROPERTIES CUDA_SEPARABLE_COMPILATION ON)

SET_TARGET_PROPERTIES(AttentionIOBenchmark
  PROPERTIES
  RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/")
