# Taken from https://github.com/deepseek-ai/DeepSeek-V3/blob/main/inference/requirements.txt
# where
# torch==2.4.1
# triton==3.0.0
# transformers==4.46.3
# safetensors==0.4.5

RUN python3 -m pip install --upgrade pip && \
    pip install \
        triton==3.0.0 \
        transformers==4.46.3 \
        safetensors==0.4.5