## LangChain needs a FAISS.
## FAISS

# These arguments are *not* global. They don't last past this layer, defined by
# the RUN docker command. See the example from here:
# https://docs.docker.com/build/guide/build-args/
# and notice how "close" or "local" the ARG's are to the "layer" it's used in.

ARG DISABLE_RAFT="OFF"
ARG COMPUTE_CAPABILITY="75;72"

# First, install dependencies, including swig, that's needed by Python.
RUN apt-get update && apt-get install -y swig && \
  git clone https://github.com/ernestyalumni/faiss.git /ThirdParty/faiss && \
  echo "This is disable raft: ${DISABLE_RAFT} and this is compute capability: ${COMPUTE_CAPABILITY}" && \
  if [ "$DISABLE_RAFT" = "ON" ]; then \
    cd /ThirdParty/faiss/ && \
    bash ./scripts/BuildForGPU.sh --disable-raft \
      --compute-capability ${COMPUTE_CAPABILITY} && cd -; \
  else \
    cd /ThirdParty/faiss/ && \
    bash ./scripts/BuildForGPU.sh --compute-capability ${COMPUTE_CAPABILITY} && \
      cd -; \
  fi

## LangChain

### https://python.langchain.com/docs/get_started/introduction
### The LangChain libraries themselves are made up of several different packages
### and we'll install 3 of them:
### langchain: Chains, agents, and retrieval strategies that make up an
### application's cognitive architecture.
### langchain-core: Base abstractions and LangChain Expression Language.
### langchain-community: Third party integrations.

RUN git clone https://github.com/ernestyalumni/langchain.git /ThirdParty/langchain && \
  cd /ThirdParty/langchain/libs/langchain && \
  git checkout master && \
  # Install editable install from source.
  # See https://python.langchain.com/docs/get_started/installation
  pip install -e . && \
  cd ../core && \
  pip install -e . && \
  cd ../community && \
  pip install -e . && \
  # Install partners, which include Anthropic, Mistral AI, Open AI, etc.
  cd ../partners && \
  cd anthropic && \
  pip install -e . && \
  cd ../mistralai && \
  pip install -e . && \
  cd ../openai && \
  pip install -e . && \
  cd ../together && \
  pip install -e .

