### Further third party code/repositories

# MoreGroq would need this.
RUN pip install groq instructor && \
  # Immediately needed for the tests for MoreGroq.
  pip install yfinance

#
#
# InServiceOfX
#
#
RUN git clone --no-checkout https://github.com/InServiceOfX/InServiceOfX.git /ThirdParty/InServiceOfX && \
  cd /ThirdParty/InServiceOfX/ && \
  git sparse-checkout init && \
  git sparse-checkout add PythonApplications/CLIChatLocal && \
  git sparse-checkout add PythonLibraries/CoreCode && \
  git sparse-checkout add PythonLibraries/HuggingFace/MoreTransformers && \
  git sparse-checkout add PythonLibraries/ThirdParties/APIs/CommonAPI && \
  git checkout master && \
  cd /
#
#
#





