### Further third party code/repositories

# MoreGroq would need this.
RUN pip install groq instructor && \
  # Immediately needed for the tests for MoreGroq.
  pip install yfinance && \
  # https://logfire.pydantic.dev/docs/#about-logfire
  # TODO: See if this has a protobuf dependency version that mismatches
  # other versions.
  #pip install logfire && \
  pip install pydantic-ai && \
  pip install pytest-asyncio && \
  # PostgreSQL database
  pip install psycopg2-binary && \
  pip install asyncpg && \
  pip install -U sentence-transformers

# For commands pg_isready and psql, to help debug PostgreSQL issues.
RUN apt-get update && apt-get install -y postgresql-client-common && \
  apt-get install -y postgresql-client && \
  # Useful with postgreSQL
  apt-get install -y iproute2

# deno is for MCP using pydantic-ai.
# https://github.com/denoland/deno_docker
COPY --from=denoland/deno:bin-2.3.5 /deno /usr/local/bin/deno

#
#
# InServiceOfX
#
#
RUN git clone --no-checkout https://github.com/InServiceOfX/InServiceOfX.git /ThirdParty/InServiceOfX && \
  cd /ThirdParty/InServiceOfX/ && \
  git sparse-checkout init && \
  git sparse-checkout add PythonApplications/CLIChatLocal && \
  git sparse-checkout add PythonLibraries/CoreCode && \
  git sparse-checkout add PythonLibraries/HuggingFace/MoreTransformers && \
  git sparse-checkout add PythonLibraries/ThirdParties/APIs/CommonAPI && \
  git checkout master && \
  cd /
#
#
#

# https://ai.pydantic.dev/install/#__tabbed_1_2
# https://docs.astral.sh/uv/getting-started/installation/
# TODO: Since Docker is already a containerized environment, it might not make
# sense to install uv.
#RUN curl -LsSf https://astral.sh/uv/install.sh | sh && \
#  source $HOME/.local/bin/env && \
#  uv add pydantic-ai

# pip install's for tools.
RUN pip install google-api-python-client youtube-transcript-api

# pip install's for applications.
RUN pip install streamlit

# HuggingFace pip installs
RUN pip install datasets