from tools.FunctionCalling import ParseFunctionAsTool
from tools.FunctionCalling.FunctionDefinition import Tool
from tools.FunctionCalling.ToolCallHandlers import ChatCompletionProcessor

from commonapi.Clients.OpenAIxGroqClient import OpenAIxGroqClient
from commonapi.Clients.OpenAIxGrokClient import OpenAIxGrokClient
from commonapi.Messages import create_user_message

from corecode.Utilities import get_environment_variable, load_environment_file
load_environment_file()
