ENV NVM_DIR /usr/local/nvm

# installs nvm (Node Version Manager)
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash && \
  #
  # It wasn't obvious that we had to invoke this shell script; see
  # https://stackoverflow.com/questions/25899912/how-to-install-nvm-in-docker
  . $NVM_DIR/nvm.sh && \
  #
  # download and install Node.js
  nvm install 20


