# https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/running.html
# Also, see
# https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch
# Check for the latest version on this page, on the left:
# https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/running.html
# Look for the PyTorch Release Notes.
# Also, try
# https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch/tags
# and click on "Tags" on the top center for the different tags.

# As of March 26, 2024
FROM nvcr.io/nvidia/pytorch:24.03-py3

# Set the working directory in the container
# https://docs.docker.com/engine/reference/builder/
ENV THIRD_PARTY=/ThirdParty
WORKDIR ${THIRD_PARTY}

# pip installations.

## Update pip.
RUN python -m pip install --upgrade pip && \
  pip install --upgrade jupyter && \
  # Reads key-value pairs from .env file to set environment variables; in
  # particular for Open AI API keys for LangChain.
  pip install --upgrade python-dotenv && \
  # For WebBaseLoader for LangChain retrieval.
  pip install --upgrade beautifulsoup4 && \
  # For Langchain, for langchain.document_loaders.DirectoryLoader
  pip install --upgrade unstructured[all-docs] && \
  # For the Vector Search Tutorial, Project 2, https://youtu.be/JEBDfGqrAUA?si=M5rZOgqQem0Hj4L6
  pip install --upgrade gradio && \
  # For ChromaDB, vector store or embedding database.
  pip install --upgrade chromadb
  