RUN python3 -m pip install --upgrade pip && \
  pip install --upgrade yfinance && \
  pip install --upgrade plotly && \
  # For saving plots locally.
  pip install --upgrade kaleido && \
  # Follow what langchain does for loading (i.e. document_loader) pdfs,
  # https://python.langchain.com/docs/how_to/document_loader_pdf/
  pip install -q --upgrade pypdf




