## LangChain

### https://python.langchain.com/docs/get_started/introduction
### The LangChain libraries themselves are made up of several different packages
### and we'll install 3 of them:
### langchain: Chains, agents, and retrieval strategies that make up an
### application's cognitive architecture.
### langchain-core: Base abstractions and LangChain Expression Language.
### langchain-community: Third party integrations.

## FAISS

ARG ENABLE_FAISS=false
ARG COMPUTE_CAPABILITY

# TODO: Update to allow for NVIDIA's RAFT.
RUN if [ "$ENABLE_FAISS" = "true" ] ; then \
    apt-get update && apt-get install -y swig && \
    git clone https://github.com/ernestyalumni/faiss.git /ThirdParty/faiss && \
    echo "This is compute capability: ${COMPUTE_CAPABILITY}" && \
    cd /ThirdParty/faiss/ && \
    bash ./scripts/BuildForGPU.sh --disable-raft \
      --compute-capability ${COMPUTE_CAPABILITY} && \
    cd / ; \
  fi

RUN git clone https://github.com/InServiceOfX/langchain.git /ThirdParty/langchain && \
  cd /ThirdParty/langchain/libs/langchain && \
  git checkout master && \
  # Install editable install from source.
  # See https://python.langchain.com/docs/get_started/installation
  pip install -e . && \
  cd ../core && \
  pip install -e . && \
  cd ../community && \
  pip install -e . && \
  # Install partners, which include Anthropic, Mistral AI, Open AI, etc.
  cd ../partners && \
  cd anthropic && \
  pip install -e . && \
  cd ../mistralai && \
  pip install -e . && \
  cd ../openai && \
  pip install -e . && \
  cd ../together && \
  pip install -e . && \
  pip install -U --quiet langmem


