### Further code/repositories from NVIDIA

## CUTLASS

RUN git clone https://github.com/InServiceOfX/cutlass.git /ThirdParty/cutlass && \
  cd /ThirdParty/cutlass && \
  git checkout master && \
  cd /


