## HuggingFace

RUN python3 -m pip install --upgrade pip && \
  # Upgrading Jinja2 to 3.1 is needed to use apply_chat_template.
  pip install --upgrade jinja2 && \
  #
  #
## transformers (hugging face), required to run LLMs as models.
  #>>> import transformers
  #>>> print(transformers.__version__)
  #4.54.0.dev0
  # 2025-07-18
  git clone https://github.com/huggingface/transformers.git /ThirdParty/transformers && \
  cd /ThirdParty/transformers && \
  # 2025-08-23
  #git checkout v4.55.4 && \
  git checkout v4.54-release && \
  # Install editable install from source.
  # See https://huggingface.co/docs/transformers/installation#installing-from-source
  pip install -e . && \
  #
  #
## accelerate - speeds up model loading for inference and training
  git clone https://github.com/huggingface/accelerate.git /ThirdParty/accelerate && \
  cd /ThirdParty/accelerate && \
  git checkout main && \
  pip install -e . && \
  #
  #
## candle (hugging face)
  git clone https://github.com/huggingface/candle.git /ThirdParty/candle && \
  cd /ThirdParty/candle && \
  git checkout main && \
  #
  #
  # See Huggingface's transformers/src/transformers/pipelines/__init__.py for
  # def pipeline(..) where if config is None and isinstance(model, str) and case
  # when if is_peft_available().
  ## PEFT (Parameter-Efficient Fine-Tuning)
  git clone https://github.com/huggingface/peft /ThirdParty/peft && \
  cd /ThirdParty/peft && \
  pip install -e . && \
  #
  #
  cd /


