def is_zipfile(opened_file) -> bool:
    """
    is_zipfile() is True if magic number appears anywhere in binary. Since we
    expect the files here to be generated by, typically in pytorch, torch.save
    or torch.jit.save, it's safe to only check the start bytes and avoid
    collisions and assume zip has only 1 file.
    """
    start = opened_file.tell()
    # Read first few bytes and match against ZIP file signature.
    local_header_magic_number = b"PK\x03\x04"
    read_bytes = opened_file.read(len(local_header_magic_number))
    opened_file.seek(start)
    return read_bytes == local_header_magic_number